config:
  location: "135.000000,35.000000"
  appid: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz012-"
  device: "Google-Home"
  ip: "192.168.0.1"
  filter1: "^(東京都).*$"
  filter2: "^(東京都|神奈川県|千葉県|埼玉県|群馬県|栃木県|茨城県|長野県|山梨県|静岡県|東京湾|相模湾|伊豆|房総半島).*$"
  tmpdir: "/tmp"
